const termsContent = [
  {
    header: 'AimHub Self-hosted License Terms',
    content: `
These terms apply to any of our Self-hosted plans.

By signing up for Aimhub Self-hosted License, you and any entity that you represent ("Customer") are unconditionally consenting to be bound by and are becoming a party to these Aimhub Subscription Terms ("Agreement") as of the date of Customer's first download of the licensed materials (the "Effective Date"). Customer's continued use of the software or any licensed materials provided by Aimhub, Inc.and/or its affiliates (“Aimhub”) , shall also constitute assent to the terms of this agreement. If you are executing this agreement on behalf of an organization, you represent that you have authority to bind your organization to this Agreement.

## **1. License and support**

1.1 Subject to the terms and conditions of this Agreement, Aimhub hereby grants to Customer and its Affiliates (as defined below) a limited, non-exclusive, non-transferable, non-sublicensable license for Customer’s and its Affiliates’ employees and contractors to internally (a) use, the Aimhub Self-hosted product (the “Software”) , solely for its internal use in connection with the development of Customer’s and/or its Affiliates’ own software; and (b) use the documentation and other materials supplied by Aimhub (the “ Aimhub Materials”). Notwithstanding anything to the contrary, Customer agrees that Aimhub and/or its licensors (as applicable) retain all right, title and interest in and to all Software incorporated in any modifications, derivative works and/or patches, and all such Software may only be used, copied, modified, displayed, distributed, or otherwise exploited in full compliance with this Agreement. The Software and Aimhub Materials are collectively referred to herein as the “Licensed Materials.” “Affiliate” means any entity(ies) controlling, controlled by, and/or under common control with a party hereto, where “control” means the ownership of more than 50% of the voting securities in such entity. “User” means each individual end-user (person or machine) of Customer and/or its Affiliates (including, without limitation, employees, agents, contractors or consultants thereof) with access to the Licensed Materials hereunder.

1.2 Subject to the terms hereof, Aimhub will provide reasonable support to Customer for the Licensed Materials. Aimhub will use reasonable commercial efforts to respond to support questions within two business days by Slack, email, in-app chat or other channels Aimhub may establish from time to time. The number of support questions is not limited.

## **2. Restrictions and responsibilities**

2.1 Except as expressly authorized in Section 1.1, Customer will not, and will not permit any third party to: use the Licensed Materials for any purpose other than as specifically authorized in Section 1, or in such a manner that would enable any unlicensed person to access the Licensed Materials; use the Licensed Materials or any other Aimhub software for timesharing or service bureau purposes or for any purpose other than permitted by this Agreement (including without limitation, sublicensing, distributing, selling, reselling any of the foregoing); except as expressly permitted herein or in writing by Aimhub; use the Licensed Materials in connection with any high risk or strict liability activity (including, without limitation, space travel, firefighting, police operations, power plant operation, military operations, rescue operations, hospital and medical operations or the like); use the Licensed Materials or software other than in accordance with this Agreement and in compliance with all applicable laws and regulations (including but not limited to any privacy laws, and laws and regulations concerning intellectual property, consumer and child protection, obscenity or defamation); or use the Licensed Materials in any manner that (1) is harmful, fraudulent, deceptive, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, or libelous (including without limitation, accessing any computer, computer system, network, software, or data without authorization, breaching the security of another user or system, and/or attempting to circumvent any User authentication or security process), (2) impersonates any person or entity, including without limitation any employee or representative of Aimhub, or (3) contains a virus, trojan horse, worm, time bomb, unsolicited bulk, commercial, or “spam” message, or other harmful computer code, file, or program (including without limitation, password guessing programs, decoders, password gatherers, keystroke loggers, cracking tools, packet sniffers, and/or encryption circumvention programs).

2.2 Customer will cooperate with Aimhub in connection with the performance of this Agreement by making available such personnel and information as may be reasonably required, and taking such other actions as Aimhub may reasonably request. Customer will also cooperate with Aimhub in establishing a password or other procedures for verifying that only designated employees of Customer have access to any administrative functions of the Licensed Materials. Customer shall maintain during the term of this Agreement and through the end of the third year after the date on which the final payment is made under this Agreement, books, records, contracts and accounts relating to the payments due Aimhub under this Agreement (collectively, the “Customer Records”). Aimhub may, at its sole expense, upon 30 days’ prior written notice to Customer and during Customer’s normal business hours and subject to industry-standard confidentiality obligations, hire an independent third party auditor to audit the Customer Records only to verify the amounts payable under this Agreement. If an audit reveals underpayment, then Customer shall promptly pay the deficiency to Aimhub plus late fees pursuant to Section 5.2. Aimhub shall bear the cost of an audit unless the audit reveals underpayment by more than 5% for the audited period, in which case Customer shall promptly pay Aimhub for the reasonable costs of the audit. In case the audit reveals underpayment of over 15%, Aimhub, in addition to the remedies available to it, will have the right to terminate this Agreement. 

2.3 Customer will be responsible for maintaining the security of Customer’s account, passwords (including but not limited to administrative and User passwords) and files, and for all uses of Customer account with or without Customer’s knowledge or consent.

2.4 A breach of this Agreement by a Customer Affiliate  will be deemed a breach of this Agreement by the Customer.

## **3. Confidentiality**

3.1 Each party (the “Receiving Party”) understands that the other party (the “Disclosing Party”) has disclosed or may disclose information relating to the Disclosing Party’s technology or business (hereinafter referred to as “Proprietary Information” of the Disclosing Party). Without limiting the foregoing, the Licensed Materials are Aimhub Proprietary Information.

3.2 The Receiving Party agrees: (i) not to divulge to any third person any such Proprietary Information, (ii) to give access to such Proprietary Information solely to those employees with a need to have access thereto for purposes of this Agreement, and (iii) to take the same security precautions to protect against disclosure or unauthorized use of such Proprietary Information that the party takes with its own proprietary information, but in no event will a party apply less than reasonable precautions to protect such Proprietary Information. The Disclosing Party agrees that the foregoing will not apply with respect to any information that the Receiving Party can document (a) is or becomes generally available to the public without any action by, or involvement of, the Receiving Party, or (b) was in its possession or known by it prior to receipt from the Disclosing Party, or (c) was rightfully disclosed to it without restriction by a third party, or (d) was independently developed without use of any Proprietary Information of the Disclosing Party. Nothing in this Agreement will prevent the Receiving Party from disclosing Proprietary Information pursuant to any judicial or governmental order, provided that the Receiving Party gives the Disclosing Party reasonable prior notice of such disclosure to contest such order. In any event, Aimhub may collect data with respect to and report on the aggregate response rate and other aggregate measures of the Licensed Materials’ performance and Customer’s usage of the Licensed Materials; provided that Aimhub will not identify Customer as the source of any such data without Customer’s prior written consent. For the avoidance of doubt, use of a third party to host the data collected and /or use of third party processors (e.g. payment processors) in the course of Aimhub’s regular business  shall not be deemed a disclosure.

3.3 Each party acknowledges and agrees that the other may suffer irreparable damage in the event of a breach of the terms of Sections 1.1, 2.1 or 3.2 of this Agreement and that such party will be entitled to seek injunctive relief (without the necessity of posting a bond) in the event of any such breach.

3.4 Both parties will have the right to disclose the existence of the relationship between the parties, but not the commercial terms of this Agreement, unless such disclosure of the Agreement terms is approved in writing by both Parties prior to such disclosure, or is included in a filing required to be made by a party with a governmental authority (provided such party will use reasonable efforts to obtain confidential treatment or a protective order) or is made on a confidential basis as reasonably necessary to potential investors or acquirers.

## **4. Intellectual property rights**

4.1 Except as expressly set forth herein, Aimhub alone (and its licensors, where applicable) will retain all intellectual property rights relating to the Licensed Materials and any suggestions, ideas, enhancement requests, feedback, code, or other recommendations provided by Customer, its Affiliates or any third party relating to the Licensed Materials (”Feedback”), which are hereby fully and exclusively assigned to Aimhub. For any rights to such Feedback that cannot be assigned, you hereby grant us a perpetual, irrevocable, non-exclusive, royalty-free, fully-paid-up, fully-transferable, worldwide license (with rights to sublicense through multiple tiers of sublicensing) under your and your licensors’ intellectual property rights to reproduce, prepare derivative works of, distribute, perform, display, and otherwise fully use, practice and exploit such Feedback for any purpose whatsoever, including but not limited to, developing, manufacturing, having manufactured, licensing, marketing, and selling, directly or indirectly, products and services using such Feedback. You agree and understand that Aimhub alone (and its licensors, where applicable) are not obligated to use, display, reproduce, or distribute any such ideas, know-how, concepts, or techniques contained in the Feedback, and you have no right to compel such use, display, reproduction, or distribution.This Agreement is not a sale and does not convey to Customer any rights of ownership in or related to the Licensed Materials, or any intellectual property rights.

4.2 Customer shall not remove, alter or obscure any of Aimhub’s (or its licensors’) copyright notices, proprietary legends, trademark or service mark attributions, patent markings or other indicia of Aimhub’s (or its licensors’) ownership or contribution from the Licensed Materials. Additionally, Customer agrees to reproduce and include Aimhub’s (and its licensors’) proprietary and copyright notices on any copies of the Licensed Materials, or on any portion thereof, including reproduction of the copyright notice. 

4.3 Customer and its licensors shall (and Customer hereby represents and warrants that they do) have and retain all right, title and interest (including, without limitation, sole ownership of) all software, information, content and data provided by or on behalf of Customer or made available or otherwise distributed through use of the Licensed Materials (“Content”) and the intellectual property rights with respect to that Content. If Aimhub receives any notice or claim that any Content, or Customer’s activities hereunder (including without limitation, with respect to any Content), infringes or violates the rights of a third party or any applicable law or regulation (a “Claim”), Customer will indemnify, defend and hold Aimhub harmless from all liability, damages, settlements, attorney fees and other costs and expenses in connection with any such Claim, as incurred. The immediately foregoing indemnity obligations are expressly conditioned on Aimhub providing Customer with prompt notice of, and reasonable cooperation and sole control over the defense and/or settlement of the applicable Claim. Subject to the foregoing, Aimhub may participate in the defense and/or settlement of any applicable Claim with counsel of its choosing at its own expense.

4.4 Aimhub will defend, indemnify and hold Customer harmless from liability and other amounts paid or payable to unaffiliated third parties resulting from the infringement or violation of any intellectual property or proprietary rights by the Licensed Materials, provided Aimhub is promptly notified of any and all threats, claims and proceedings related thereto and given reasonable assistance and the opportunity to assume sole control over defense and settlement thereof. Subject to the foregoing, Customer may participate in the defense and/or settlement of any claim that is indemnifiable by Aimhub with counsel of its choosing at its own expense. The foregoing obligations do not apply with respect to portions or components of the Licensed Materials (i) not created by Aimhub, (ii) that are modified after delivery by Aimhub, (iii) combined with other products, processes or materials where the alleged infringement relates to such combination, (iv) where Customer continues allegedly infringing activity after being notified thereof or after being informed of modifications that would have avoided the alleged infringement, or (v) where Customer’s use of the Licensed Materials is not strictly in accordance with this Agreement and all related documentation.

## **5. Payment of fees**

5.1 Customer will pay Aimhub the then applicable fees described in the order form or quote for the Licensed Materials in accordance with the terms therein (the “Fees”). In case Fees in such order form or quote are based on certain usage levels and limitations,   andCustomer’s use of the Licensed Materials exceeds the limitations as set  set forth on the order form or quote or otherwise requires the payment of additional fees , Customer shall be billed for such usage and Customer agrees to pay the additional fees in the manner provided herein. Aimhub reserves the right to change the Fees or applicable charges and to institute new charges and Fees at the end of the Initial Service Term or then current renewal term, upon thirty (30) days prior notice to Customer (which may be sent by email). If Customer believes that Aimhub has billed Customer incorrectly, Customer must contact Aimhub no later than 60 days after the closing date on the first billing statement in which the error or problem appeared, in order to receive an adjustment or credit. Inquiries should be directed to Company’s customer support department (support@Aimhub.com).

5.2 Aimhub may choose to bill through an invoice, in which case, full payment for invoices issued in any given month must be received by Aimhub according to the payment terms specified in the invoice. Unpaid amounts are subject to a finance charge of 1.5% per month on any outstanding balance, or the maximum permitted by law, whichever is lower, plus all expenses of collection and may result in immediate termination of Service. Customer shall be responsible for all taxes associated with the Licenses Materials other than U.S. taxes based on Aimhub’s net income.

5.3 Our fees do not include any taxes, levies, duties or similar governmental assessments of any nature, including, for example, value-added, sales, GST, use or withholding taxes, assessable by any jurisdiction whatsoever in relation to your purchases under this Agreement (collectively, the “Taxes”). You are solely responsible for paying all Taxes associated with your purchases hereunder. If we have a legal obligation to pay or collect Taxes for which you are responsible for under this Clause 4.3, we shall invoice you and you shall pay that amount to us unless you provide us with a valid tax exemption certificate authorised by the appropriate taxing authority. We shall calculate applicable Taxes based on your billing address as detailed on the relevant Order Form or Quote (it is your duty to inform us if Taxes should be assessed on a different address). You shall promptly notify us of any changes to any of your addresses specified in a Order Form or Quote. Taxes shall not be deducted from or set-off against the fees in the applicable Order Form or Quote.

5.4 Subject to earlier termination as provided below, this Agreement is for the Initial Service Term as specified in the order form or quote, and shall be automatically renewed for additional periods of the same duration as the Initial Service Term (collectively, the “Term”), unless either party requests termination with at least thirty (30) days notice.

## **6. Termination**

6.1 This Agreement shall continue until terminated in accordance with this Section 6. Either party may terminate this Agreement upon 30 days’ written notice to the other party hereto in the event that Customer has no then-current subscription with respect to the Licensed Materials. In case the Agreement is terminated for convenience by the Customer, Customer shall promptly pay any outstanding Fees due hereunder.

6.2 Customer may terminate this Agreement at any time upon written notice to Aimhub. Either party may terminate this Agreement immediately upon 30 days’ written notice to the other party in the event of any material breach of this Agreement (including without limitation, any breach of Section 2.2 and/or failure to pay any amounts when due hereunder) by such party where such material breach is not cured during such notice period.

6.3 Either party may terminate this Agreement, without notice, (i) upon the institution by or against the other party of insolvency, receivership or bankruptcy proceedings (provided such proceedings are not dismissed within one hundred twenty (120) days of such institution), (ii) upon the other party’s making an assignment for the benefit of creditors, or (iii) upon the other party’s dissolution or ceasing to do business without a successor.

6.4 Customer’s rights to the Licensed Materials, and any licenses granted hereunder, shall terminate upon any termination of this Agreement. In the event that Customer terminates this Agreement pursuant to the second sentence of Section 6.2 above, Aimhub will refund to Customer a pro-rated portion of pre-paid Fees for Services not actually received by Customer as of the date of such termination. The following Sections will survive any termination of this Agreement: 2 through 6 (except for Section 4.3), and 9 through 11.

## **7. Updates**

We may from time to time in our sole discretion develop and provide updates for for Licensed Materials and/or otherwise make changes to all or parts of Licensed Materials, which may include upgrades, bug fixes, patches, other error corrections, and/or new features (collectively, including related documentation, “Updates”). Updates may also modify or delete in their entirety certain content, features, and functionality. You agree that we have no obligation to provide any Updates or to continue to provide or enable any particular content, features, or functionality.

## **8. Limited Warranty; Customer Software Security**

Aimhub represents and warrants that (i) it has all rights and licenses necessary for it to perform its obligations hereunder, and (ii) it will not knowingly include, in any Aimhub software released to the public and provided to Customer hereunder, any computer code or other computer instructions, devices or techniques, including without limitation those known as disabling devices, trojans, or time bombs, that are intentionally designed to disrupt, disable, harm, infect, defraud, damage, or otherwise impede in any manner, the operation of a network, computer program or computer system or any component thereof, including its security or user data. If, at any time, Aimhub fails to comply with the warranty in this Section, Customer may promptly notify Aimhub in writing of any such noncompliance. Aimhub will, within thirty (30) days of receipt of such written notification, either correct the noncompliance or provide Customer with a plan for correcting the noncompliance. If the noncompliance is not corrected or if a reasonably acceptable plan for correcting them is not established during such period, Customer may terminate this Agreement as its sole and exclusive remedy for such noncompliance.

## **9. Limitation of liability**

EXCEPT WITH RESPECT TO BREACH(ES) OF SECTION 1.1 AND/OR 2.1, IN NO EVENT WILL EITHER PARTY OR THEIR LICENSORS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF THE LICENSED MATERIALS OR ANYTHING PROVIDED IN CONNECTION WITH THIS AGREEMENT, ANY DELAY OR INABILITY TO USE THE LICENSED MATERIALS OR ANYTHING PROVIDED IN CONNECTION WITH THIS AGREEMENT OR OTHERWISE ARISING FROM THIS AGREEMENT, INCLUDING WITHOUT LIMITATION, LOSS OF REVENUE OR ANTICIPATED PROFITS OR LOST BUSINESS OR LOST SALES, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE, EVEN IF SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. EXCEPT WITH RESPECT TO BREACH(ES) OF SECTION 1.1 AND/OR 2.1, THE TOTAL LIABILITY OF EACH PARTY AND ITS LICENSORS, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE OR STRICT LIABILITY), OR OTHERWISE, WILL NOT EXCEED, IN THE AGGREGATE, THE GREATER OF (i) ONE THOUSAND DOLLARS ($1,000), OR (ii) THE FEES PAID TO AimHub HEREUNDER IN ONE YEAR PERIOD ENDING ON THE DATE THAT A CLAIM OR DEMAND IS FIRST ASSERTED. THE FOREGOING LIMITATIONS WILL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.

## **10. U.S. Government Matters**

Notwithstanding anything else, Customer may not provide to any person or export or re-export or allow the export or re-export of the Licensed Materials or any software or anything related thereto or any direct product thereof (collectively “Controlled Subject Matter”), in violation of any restrictions, laws or regulations of the United States Department of Commerce, the United States Department of Treasury Office of Foreign Assets Control, or any other United States or foreign agency or authority. Without limiting the foregoing Customer acknowledges and agrees that the Controlled Subject Matter will not be used or transferred or otherwise exported or re-exported to countries as to which the United States maintains an embargo (collectively, “Embargoed Countries”), or to or by a national or resident thereof, or any person or entity on the U.S. Department of Treasury’s List of Specially Designated Nationals or the U.S. Department of Commerce’s Table of Denial Orders (collectively, “Designated Nationals”). The lists of Embargoed Countries and Designated Nationals are subject to change without notice. Use of the Licensed Materials is representation and warranty that the User is not located in, under the control of, or a national or resident of an Embargoed Country or Designated National. The Controlled Subject Matter may use or include encryption technology that is subject to licensing requirements under the U.S. Export Administration Regulations. As defined in FAR section 2.101, any software and documentation provided by AimHub are “commercial items” and according to DFAR section 252.2277014(a)(1) and (5) are deemed to be “commercial computer software” and “commercial computer software documentation.” Consistent with DFAR section 227.7202 and FAR section 12.212, any use modification, reproduction, release, performance, display, or disclosure of such commercial software or commercial software documentation by the U.S. Government will be governed solely by the terms of this Agreement and will be prohibited except to the extent expressly permitted by the terms of this Agreement.

## **11. Miscellaneous**

If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable. This Agreement is not assignable, transferable or sublicensable by either party without the other party’s prior written consent, not to be unreasonably withheld or delayed; provided that either party may transfer and/or assign this Agreement to a successor in the event of a sale of all or substantially all of its business or assets to which this Agreement relates. Both parties agree that this Agreement is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement, and that all waivers and modifications must be in a writing signed or otherwise agreed to by each party, except as otherwise provided herein. No agency, partnership, joint venture, or employment is created as a result of this Agreement and neither party has any authority of any kind to bind the other in any respect whatsoever. In any action or proceeding to enforce rights under this Agreement, the prevailing party will be entitled to recover costs and attorneys’ fees. All notices under this Agreement will be in writing and will be deemed to have been duly given when received, if personally delivered; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; and upon receipt, if sent by certified or registered mail (return receipt requested), postage prepaid. AimHub will not be liable for any loss resulting from a cause over which it does not have direct control. This Agreement will be governed by the laws of the State of California, U.S.A. without regard to its conflict of laws provisions. The federal and state courts sitting in San Francisco County, California, U.S.A. will have proper and exclusive jurisdiction and venue with respect to any disputes arising from or related to the subject matter of this Agreement.

## **12. Data privacy**

Where we process any customer personal data in connection with this Agreement, we can enter into a separate GDPR Data Processing Agreement upon request, the exact terms of which will vary depending on the nature of the installation, how personal data is being processed, and where it is stored. Our standard form agreement can be viewed **[here](https://docs.google.com/document/d/1xfpP1SCFoI1qSKM6rEt9VqRLRUEXiKj9_0Tvv2mP928/edit?usp=sharing)**.
    `,
  },
  {
    header: 'AimHub Open-Source Software (FOSS) License Terms',
    content: `
You can find a copy of our FOSS License Terms in our [GitHub repository](https://github.com/aimhubio/aim/blob/main/LICENSE). We license the Aim under the Apache License. 
    `,
  },
];

export default termsContent;
